#!/usr/bin/env python3
"""
Orbit Grab — bundler
====================
Builds a single self-contained LocalScript (dist/OrbitGrab_AllInOne.client.lua)
out of the Rojo module tree, for people who would rather paste one file into
Studio than set up Rojo.

It also copies the standalone server script next to it.

Usage:  python3 tools/bundle.py
"""

import os
import re
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")
DIST = os.path.join(ROOT, "dist")

RS = os.path.join(SRC, "ReplicatedStorage", "OrbitGrab")

# (variable name, file name) — order matters: dependencies first
MODULES = [
    ("Config", "Config.lua"),
    ("Orbit", "Orbit.lua"),
    ("FX", "FX.lua"),
    ("UI", "UI.lua"),
    ("Carrier", "Carrier.lua"),
    ("OrbitGrab", "init.lua"),
]

CLIENT = os.path.join(SRC, "StarterPlayer", "StarterPlayerScripts", "OrbitGrabClient.client.lua")
SERVER = os.path.join(SRC, "ServerScriptService", "OrbitGrabServer.server.lua")

HEADER = """--!nolint
--[=[
\tORBIT GRAB  ·  all-in-one client build  (generated — do not edit)
\t====================================================================
\tThis file is the Rojo project flattened into one LocalScript.

\tINSTALL (30 seconds, no Rojo needed)
\t  1. Studio ▸ StarterPlayer ▸ StarterPlayerScripts
\t     → right-click ▸ Insert Object ▸ LocalScript
\t     → paste this whole file in, name it "OrbitGrab".
\t  2. (Multiplayer only) Studio ▸ ServerScriptService
\t     → right-click ▸ Insert Object ▸ Script
\t     → paste dist/OrbitGrabServer.server.lua in.
\t  3. Press Play.

\tControls are listed in-game (press J), and every number is tunable in
\tthe CONFIG block at the top of this file.

\tGenerated by tools/bundle.py from src/. Edit the source, not this file.
--]=]

"""


def read(path):
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()


def strip_requires(source, names):
    """Turn `require(script.Parent.Foo)` into a reference to the local `Foo`."""
    for name in names:
        source = re.sub(
            r"require\(\s*script\.Parent(?:\.Parent)*\s*[.::]\s*[\"']?"
            + name
            + r"[\"']?\s*\)",
            name,
            source,
        )
    return source


def strip_comments(source):
    """Rough Lua comment stripper — only used to sanity-check the bundle,
    so it doesn't need to be perfect."""
    out = []
    i, n = 0, len(source)
    while i < n:
        if source.startswith("--[[", i) or source.startswith("--[=[", i):
            close = "]]" if source[i + 2] == "[" else "]=]"
            j = source.find(close, i + 4)
            i = n if j == -1 else j + len(close)
        elif source.startswith("--", i):
            j = source.find("\n", i)
            i = n if j == -1 else j
        else:
            out.append(source[i])
            i += 1
    return "".join(out)


def main():
    os.makedirs(DIST, exist_ok=True)
    names = [n for n, _ in MODULES]

    chunks = [HEADER]
    for var, fname in MODULES:
        body = read(os.path.join(RS, fname)).strip("\n")
        body = strip_requires(body, names)
        chunks.append(
            "----------------------------------------------------------------------\n"
            "--  MODULE: %s (%s)\n"
            "----------------------------------------------------------------------\n"
            "local %s = (function()\n%s\nend)()\n\n" % (var, fname, var, body)
        )

    client = read(CLIENT).strip("\n")
    # the client pulls the package out of ReplicatedStorage; in the bundle it's a local
    client = re.sub(
        r"require\(\s*[\w\.:]+\s*:\s*WaitForChild\(\s*[\"']OrbitGrab[\"']\s*\)\s*\)",
        "OrbitGrab",
        client,
    )
    # drop the now-pointless ReplicatedStorage service lookup if unused
    if "ReplicatedStorage" not in client.replace(
        'local ReplicatedStorage   = game:GetService("ReplicatedStorage")', ""
    ):
        client = client.replace(
            'local ReplicatedStorage   = game:GetService("ReplicatedStorage")\n', ""
        )

    chunks.append(
        "----------------------------------------------------------------------\n"
        "--  CLIENT BOOTSTRAP (OrbitGrabClient.client.lua)\n"
        "----------------------------------------------------------------------\n"
        + client
        + "\n"
    )

    bundle = "".join(chunks)

    code_only = strip_comments(bundle)
    if "require(" in code_only:
        for i, line in enumerate(code_only.split("\n"), 1):
            if "require(" in line:
                raise SystemExit(
                    "Unresolved require on line %d: %s" % (i, line.strip())
                )

    out = os.path.join(DIST, "OrbitGrab_AllInOne.client.lua")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(bundle)

    shutil.copyfile(SERVER, os.path.join(DIST, "OrbitGrabServer.server.lua"))

    print("wrote %s (%d lines)" % (out, bundle.count("\n") + 1))
    print("wrote %s" % os.path.join(DIST, "OrbitGrabServer.server.lua"))


if __name__ == "__main__":
    main()
